name: Frontend test
on:
  push:
    paths:
        - 'Ice-Quef-test/**'
  
jobs:
  jest:
    runs-on: ubuntu-latest

    defaults:
        run: # specify working directory
          working-directory: Ice-Quef-test
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies with npm
        run: npm ci --force
      
      - name: Run Jest
        run: npm run test